// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQZF3qbc71owutpib0sb3HSefJ3z_bMpc',
    appId: '1:54335721188:web:62e4e73d552c4afa6566f1',
    messagingSenderId: '54335721188',
    projectId: 'chat-63ea5',
    authDomain: 'chat-63ea5.firebaseapp.com',
    storageBucket: 'chat-63ea5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwOcnp2nVlnxQlHnkS9kl53B0SFWHKqCs',
    appId: '1:54335721188:android:71ea4cd00db03c9d6566f1',
    messagingSenderId: '54335721188',
    projectId: 'chat-63ea5',
    storageBucket: 'chat-63ea5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG76PlmO1IM48Yn4TuXBr_0aHv7OtEi04',
    appId: '1:54335721188:ios:a68bbb83b5ac08c36566f1',
    messagingSenderId: '54335721188',
    projectId: 'chat-63ea5',
    storageBucket: 'chat-63ea5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG76PlmO1IM48Yn4TuXBr_0aHv7OtEi04',
    appId: '1:54335721188:ios:e232955ccaf1f3de6566f1',
    messagingSenderId: '54335721188',
    projectId: 'chat-63ea5',
    storageBucket: 'chat-63ea5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
